USE bazarboost;
SELECT * FROM usuarios;
SELECT * FROM productos;
SELECT * FROM descuentos;
SELECT * FROM resenias;
SELECT * FROM categorias;
SELECT * FROM productoscarrito;
SELECT * FROM direcciones;
SELECT * FROM metodospago;
SELECT * FROM facturas;
SELECT * FROM productosfacturas;
SELECT * FROM roles;
SELECT * FROM usuariosroles;